#!/bin/bash
#SBATCH --job-name=velvet
#SBATCH --output=velvet_%j.out
#SBATCH --error=velvet_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G#!/bin/bash
#SBATCH --job-name=velvet
#SBATCH --output=velvet_%j.out
#SBATCH --error=velvet_%j.err
#SBATCH --time=02:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G
#SBATCH --partition=AMD9554-common

VELVETH="/home/STUDY/FBMF/bioinformatics/soft/velvet/velveth"
VELVETG="/home/STUDY/FBMF/bioinformatics/soft/velvet/velvetg"
R1="/home/STUDY/FBMF/bioinformatics/genome_de_novo/7_S4_L001_R1_001.fastq"
R2="/home/STUDY/FBMF/bioinformatics/genome_de_novo/7_S4_L001_R2_001.fastq"

BASE_DIR="$HOME/hw4/velvet_results"

K_VALUES=(11 21 31)

mkdir -p $BASE_DIR

for K in "${K_VALUES[@]}"; do
    OUT_DIR="${BASE_DIR}/k${K}"
    echo "=== Сборка для k = ${K} в ${OUT_DIR} ==="
    mkdir -p $OUT_DIR
    $VELVETH $OUT_DIR $K -fastq -shortPaired $R1 $R2
    $VELVETG $OUT_DIR -ins_length 300
done

echo "Все сборки завершены."
