set -e
true
true
/home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/bin/spades-core /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K21/configs/config.info /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K21/configs/isolate_mode.info
/home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/bin/spades-core /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K33/configs/config.info /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K33/configs/isolate_mode.info
/home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/bin/spades-core /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K55/configs/config.info /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K55/configs/isolate_mode.info
/home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/bin/spades-core /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/configs/config.info /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/configs/isolate_mode.info
/usr/bin/python3 /home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/share/spades/spades_pipeline/scripts/copy_files.py /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/before_rr.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/before_rr.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/assembly_graph_after_simplification.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/assembly_graph_after_simplification.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/final_contigs.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/contigs.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/first_pe_contigs.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/first_pe_contigs.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/strain_graph.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/strain_graph.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/scaffolds.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/scaffolds.fasta /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/scaffolds.paths /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/scaffolds.paths /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/assembly_graph_with_scaffolds.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/assembly_graph_with_scaffolds.gfa /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/assembly_graph.fastg /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/assembly_graph.fastg /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/K77/final_contigs.paths /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/contigs.paths
true
/usr/bin/python3 /home/STUDY/FBMF/bioinformatics/soft/SPAdes-4.2.0-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/scaffolds.fasta --misc_dir /home/STUDY/FBMF/studfbmf02_08/hw4/spades_improved/misc --threshold_for_breaking_scaffolds 3
true
